### ISSUE TITLE
SnSnEd | Freezing Window at 2. stamp

### ISSUE THREAD

**Issue by KiwiKaiser** [SvenWollinger/SnipSniper#18] opened 2021-05-14 17:30 UTC
When stamping with the SmartPixel tool for the second time, the SnSnEd window freezes for large images. There are no problems with the first drawing. No further edits are possible afterwards. Right-clicking does not close the window, nor is the image saved. (Occurred with a less performant CPU)

**Comment by SvenWollinger** [comment] 2021-09-02 08:36
Are you still experiencing this? If so, please take a video of it or write me again with steps to reproduce.
Since i cant see any issues on my side and we have no other reports im closing this for now.
Thanks!

**Closed by SvenWollinger** 2021-09-02 08:36 UTC
Labels: bug
